name: agri_advisor
description: Agricultural Advisor Mobile App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.0
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_markdown: ^0.6.18
  permission_handler: ^11.3.1
  intl: ^0.19.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
